/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 habitacion2.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function HabitacionComponent(props) {
  const { nodes, materials } = useGLTF("/models/habitacion2.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[0, -0.399, 0]} scale={[1.173, 1, 1]}>
        <mesh
          geometry={nodes.Cube002_1.geometry}
          material={materials.paredes}
        />
        <mesh
          geometry={nodes.Cube002_2.geometry}
          material={materials.cornisa}
        />
      </group>
      <mesh
        geometry={nodes.table.geometry}
        material={materials.patas_escritorio}
        position={[-3.491, 2.692, -1.031]}
        scale={[1.116, 0.105, 2.157]}
      />
      <mesh
        geometry={nodes.suport_monitors.geometry}
        material={materials.ALZADOR}
        position={[-4.294, 3.19, -0.996]}
        scale={[1.094, 0.099, 2.161]}
      />
      <mesh
        geometry={nodes["table-pied"].geometry}
        material={materials.SILLAS_ruedas}
        position={[-3.491, 1.943, -1.031]}
      />
      <group position={[-4.165, 4.028, 0.048]} scale={1.245}>
        <mesh
          geometry={nodes.Cube009_1.geometry}
          material={materials.button_negro}
        />
        <mesh
          geometry={nodes.Cube009_2.geometry}
          material={materials.pantalla_tv}
        />
      </group>
      <group position={[-4.092, 4.022, -1.937]} scale={1.205}>
        <mesh
          geometry={nodes.Cube010_1.geometry}
          material={materials.button_negro}
        />
        <mesh
          geometry={nodes.Cube010_2.geometry}
          material={materials.pantalla_tv}
        />
      </group>
      <group position={[-2.946, 2.85, 0.12]} scale={[0.303, 0.065, 0.67]}>
        <mesh geometry={nodes.Cube011_1.geometry} material={materials.pedal} />
        <mesh
          geometry={nodes.Cube011_2.geometry}
          material={materials["blanco.001"]}
        />
      </group>
      <group
        position={[-2.985, 2.91, -0.991]}
        rotation={[0, 0, -Math.PI]}
        scale={[-0.189, -0.087, -0.115]}
      >
        <mesh geometry={nodes.Cube037_1.geometry} material={materials.pedal} />
        <mesh
          geometry={nodes.Cube037_2.geometry}
          material={materials["blanco.001"]}
        />
      </group>
      <mesh
        geometry={nodes.soutien_stylo.geometry}
        material={nodes.soutien_stylo.material}
        position={[-3.845, 2.775, -2.807]}
        scale={[-0.057, -0.12, -0.051]}
      />
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={nodes.Cylinder.material}
        position={[-3.846, 2.994, -2.805]}
        scale={[0.078, 0.305, 0.079]}
      />
      <group position={[-2.944, 2.868, -1.706]}>
        <mesh geometry={nodes.Cube042_1.geometry} material={materials.pedal} />
        <mesh
          geometry={nodes.Cube042_2.geometry}
          material={materials["blanco.001"]}
        />
      </group>
      <mesh
        geometry={nodes.tapis_de_souris.geometry}
        material={nodes.tapis_de_souris.material}
        position={[-2.972, 2.804, -0.981]}
        scale={[0.287, 0.041, 0.287]}
      />
      <mesh
        geometry={nodes.cable.geometry}
        material={materials.cable}
        position={[-4.039, 2.851, -0.72]}
      />
      <mesh
        geometry={nodes.cable001.geometry}
        material={materials.cable}
        position={[-3.96, 2.892, -0.43]}
      />
      <mesh
        geometry={nodes.cable002.geometry}
        material={materials.cable}
        position={[-3.994, 2.915, 0.176]}
      />
      <mesh
        geometry={nodes.haut_parleur.geometry}
        material={materials.ALTAVOZ1}
        position={[-3.931, 2.541, 2.461]}
        scale={[0.675, 1.347, 0.701]}
      >
        <mesh
          geometry={nodes.Cylinder003.geometry}
          material={materials.ALTAVOZ2}
          position={[0.474, 0.671, 0.033]}
          scale={[1.886, 0.994, 1.816]}
        >
          <mesh
            geometry={nodes.Cylinder001.geometry}
            material={materials.ALTAVOZ3}
            position={[0.059, -0.072, 0]}
            scale={[0.786, 0.747, 0.786]}
          >
            <mesh
              geometry={nodes.Roundcube.geometry}
              material={nodes.Roundcube.material}
              scale={[0.092, 0.153, 0.153]}
            />
          </mesh>
          <mesh
            geometry={nodes.Cylinder002.geometry}
            material={materials.ALTAVOZ3}
            position={[0.052, -0.997, 0]}
            scale={[0.786, 0.747, 0.786]}
          >
            <mesh
              geometry={nodes.Roundcube001.geometry}
              material={materials.ALTAVOZ2}
              position={[-0.019, 0, 0]}
              scale={[0.092, 0.153, 0.153]}
            />
          </mesh>
        </mesh>
      </mesh>
      <mesh
        geometry={nodes.haut_parleur_2.geometry}
        material={materials.ALTAVOZ1}
        position={[-3.931, 2.437, -4.612]}
        scale={[0.675, 1.347, 0.701]}
      >
        <mesh
          geometry={nodes.Cylinder006.geometry}
          material={materials.ALTAVOZ2}
          position={[0.474, 0.671, 0.033]}
          scale={[1.886, 0.994, 1.816]}
        >
          <mesh
            geometry={nodes.Cylinder004.geometry}
            material={materials.ALTAVOZ3}
            position={[0.059, -0.072, 0]}
            scale={[0.786, 0.747, 0.786]}
          >
            <mesh
              geometry={nodes.Roundcube002.geometry}
              material={materials.ALTAVOZ2}
              scale={[0.092, 0.153, 0.153]}
            />
          </mesh>
          <mesh
            geometry={nodes.Cylinder005.geometry}
            material={materials.ALTAVOZ3}
            position={[0.052, -0.997, 0]}
            scale={[0.786, 0.747, 0.786]}
          >
            <mesh
              geometry={nodes.Roundcube003.geometry}
              material={materials.ALTAVOZ2}
              position={[-0.019, 0, 0]}
              scale={[0.092, 0.153, 0.153]}
            />
          </mesh>
        </mesh>
      </mesh>
      <mesh
        geometry={nodes.note_de_musique.geometry}
        material={materials.persiana}
        position={[-3.319, 3.695, 3.482]}
        scale={0.272}
      />
      <mesh
        geometry={nodes.Cylinder007.geometry}
        material={materials.lampara_pies}
        position={[-2.598, 0.753, -4.969]}
      >
        <mesh
          geometry={nodes.NurbsPath_1?.geometry}
          material={materials.aluminium}
          position={[3.609, -1.311, 4.627]}
          rotation={[0, 0.18, 0]}
        />
        <mesh
          geometry={nodes.Sphere.geometry}
          material={materials.lampara_tete}
          position={[3.609, -1.311, 4.627]}
          rotation={[0, 0.18, 0]}
        />
        <mesh
          geometry={nodes.Sphere001_1?.geometry}
          material={nodes.Sphere001_1?.material}
          position={[3.609, -1.311, 4.627]}
          rotation={[0, 0.18, 0]}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube.geometry}
        material={materials.SILLAS1}
        position={[-0.42, 3.218, -0.899]}
        scale={1.904}
      />
      <mesh
        geometry={nodes.Cube001.geometry}
        material={materials.SILLAS1}
        position={[-1.25, 2.27, -0.895]}
        scale={[0.782, 0.116, 0.695]}
      />
      <mesh
        geometry={nodes.Cube002.geometry}
        material={materials.SILLAS_brasos}
        position={[-1.183, 2.718, -1.692]}
        scale={1.904}
      />
      <mesh
        geometry={nodes.Cube003.geometry}
        material={materials.SILLAS_ruedas}
        position={[-1.119, 2.499, -1.701]}
        rotation={[0, 0, -0.151]}
        scale={[0.592, 0.648, 1]}
      />
      <mesh
        geometry={nodes.Cylinder008.geometry}
        material={materials.SILLAS_ruedas}
        position={[-0.94, 1.609, -0.902]}
        scale={[0.097, 0.447, 0.097]}
      />
      <mesh
        geometry={nodes.Torus.geometry}
        material={materials.cable}
        position={[-0.948, 1.116, -0.91]}
        scale={0.175}
      />
      <mesh
        geometry={nodes.Torus001.geometry}
        material={materials.cable}
        position={[-0.947, 2.025, -0.902]}
        scale={0.105}
      />
      <mesh
        geometry={nodes.Cube004.geometry}
        material={materials.SILLAS_brasos}
        position={[-0.954, 2.288, -0.883]}
        scale={[0.409, 0.067, 0.073]}
      />
      <mesh
        geometry={nodes.Cube005.geometry}
        material={materials.SILLAS_brasos}
        position={[-0.954, 2.288, -0.883]}
        rotation={[-Math.PI, 1.566, -Math.PI]}
        scale={[0.409, 0.067, 0.073]}
      />
      <mesh
        geometry={nodes.Cube006.geometry}
        material={materials.SILLAS_brasos}
        position={[-0.954, 2.278, -0.883]}
        rotation={[0, -1.566, 0]}
        scale={[0.409, 0.067, 0.073]}
      />
      <mesh
        geometry={nodes.Cube007.geometry}
        material={materials.SILLAS_brasos}
        position={[-0.954, 2.288, -0.911]}
        rotation={[-Math.PI, 0.017, -Math.PI]}
        scale={[0.409, 0.067, 0.073]}
      />
      <mesh
        geometry={nodes.Cylinder009.geometry}
        material={materials.SILLAS_ruedas}
        position={[-0.958, 0.996, -0.158]}
        rotation={[-1.567, -0.13, -0.25]}
        scale={[0.097, 0.069, 0.097]}
      />
      <mesh
        geometry={nodes.Cylinder011.geometry}
        material={materials.SILLAS_ruedas}
        position={[-1.71, 0.985, -0.918]}
        rotation={[-1.682, -0.068, -1.305]}
        scale={[0.097, 0.069, 0.097]}
      />
      <mesh
        geometry={nodes.Cylinder012.geometry}
        material={materials.SILLAS_ruedas}
        position={[-0.944, 0.985, -1.68]}
        rotation={[-1.696, 0.036, -2.128]}
        scale={[0.097, 0.069, 0.097]}
      />
      <mesh
        geometry={nodes.Cylinder013.geometry}
        material={materials.SILLAS_ruedas}
        position={[-0.189, 0.985, -0.884]}
        rotation={[-1.441, 0.002, 1.305]}
        scale={[0.097, 0.069, 0.097]}
      />
      <mesh
        geometry={nodes.Cylinder010.geometry}
        material={materials.aluminium}
        position={[-0.887, 0.706, -5.657]}
        scale={[0.425, 0.051, 0.425]}
      />
      <mesh
        geometry={nodes.Cylinder014.geometry}
        material={materials.aluminium}
        position={[-0.887, 1.873, -5.657]}
        scale={[0.425, 0.051, 0.425]}
      />
      <mesh
        geometry={nodes.Cube008.geometry}
        material={materials.pedal}
        position={[-0.889, 0.775, -5.184]}
        rotation={[-2.984, 1.566, -Math.PI]}
        scale={[0.136, 0.031, 0.102]}
      />
      <mesh
        geometry={nodes.Cube009.geometry}
        material={materials.sobre_escritorio}
        position={[2.883, 2.857, -5.742]}
        scale={[2.623, 0.131, 1]}
      />
      <mesh
        geometry={nodes.Cube010.geometry}
        material={materials.caja}
        position={[2.977, 6.12, -6.066]}
        scale={[1.768, 0.131, 0.504]}
      />
      <mesh
        geometry={nodes.Cube011.geometry}
        material={materials.patas_escritorio}
        position={[-0.69, -0.458, 0]}
      />
      <mesh
        geometry={nodes.Cube012.geometry}
        material={materials.patas_escritorio}
        position={[4.321, 1.697, -5.658]}
      />
      <mesh
        geometry={nodes.Cube013.geometry}
        material={materials.cajon}
        position={[4.321, 2.265, -4.8]}
        scale={[1, 1.081, 1]}
      />
      <mesh
        geometry={nodes.Cube014.geometry}
        material={materials.cajon}
        position={[4.321, 1.739, -5.612]}
        scale={[1, 1.099, 1]}
      />
      <mesh
        geometry={nodes.Cube015.geometry}
        material={materials.cajon}
        position={[4.321, 1.211, -5.608]}
        scale={[1, 1.087, 1]}
      />
      <mesh
        geometry={nodes.Roundcube004.geometry}
        material={materials.sobre_escritorio}
        position={[3.772, 2.25, -3.89]}
        scale={[0.093, 0.093, 0.048]}
      />
      <mesh
        geometry={nodes.Roundcube005.geometry}
        material={materials.sobre_escritorio}
        position={[4.867, 2.25, -3.89]}
        scale={[0.093, 0.093, 0.048]}
      />
      <mesh
        geometry={nodes.Roundcube006.geometry}
        material={materials.sobre_escritorio}
        position={[3.772, 1.762, -4.731]}
        scale={[0.093, 0.093, 0.048]}
      />
      <mesh
        geometry={nodes.Roundcube007.geometry}
        material={materials.sobre_escritorio}
        position={[4.867, 1.762, -4.731]}
        scale={[0.093, 0.093, 0.048]}
      />
      <mesh
        geometry={nodes.Roundcube008.geometry}
        material={materials.sobre_escritorio}
        position={[3.772, 1.192, -4.724]}
        scale={[0.093, 0.093, 0.048]}
      />
      <mesh
        geometry={nodes.Roundcube009.geometry}
        material={materials.sobre_escritorio}
        position={[4.867, 1.192, -4.724]}
        scale={[0.093, 0.093, 0.048]}
      />
      <group position={[4.279, 3.721, -5.517]} scale={[0.784, 0.739, 0.604]}>
        <mesh geometry={nodes.Cube066.geometry} material={materials.tv} />
        <mesh
          geometry={nodes.Cube066_1.geometry}
          material={materials.pantalla_tv}
        />
      </group>
      <mesh
        geometry={nodes.Sphere002.geometry}
        material={materials.metal}
        position={[3.563, 5.125, -5.119]}
        rotation={[0.062, 0.072, 0.829]}
        scale={[0.078, 0.104, 0.093]}
      />
      <mesh
        geometry={nodes.Sphere003.geometry}
        material={materials.metal}
        position={[4.868, 5.194, -5.263]}
        rotation={[-0.078, -0.008, -0.676]}
        scale={[0.078, 0.104, 0.093]}
      />
      <mesh
        geometry={nodes.Sphere004.geometry}
        material={materials.metal}
        position={[4.268, 4.423, -5.263]}
        scale={0.228}
      />
      <mesh
        geometry={nodes.Cylinder015.geometry}
        material={materials.aluminium}
        position={[4.268, 4.423, -5.246]}
        scale={[0.275, 0.103, 0.275]}
      />
      <mesh
        geometry={nodes.Plane.geometry}
        material={materials.libro_azul}
        position={[3.978, 6.227, -5.961]}
        rotation={[0, 1.546, 0]}
        scale={[0.381, 0.44, 0.164]}
      >
        <mesh
          geometry={nodes.Cube017.geometry}
          material={nodes.Cube017.material}
          position={[0.028, 0.815, -0.014]}
          scale={[0.886, 0.756, 0.849]}
        />
      </mesh>
      <mesh
        geometry={nodes.Plane001.geometry}
        material={materials.libro_amarillo}
        position={[3.615, 6.227, -5.961]}
        rotation={[0, 1.546, 0]}
        scale={[0.381, 0.44, 0.164]}
      >
        <mesh
          geometry={nodes.Cube018.geometry}
          material={nodes.Cube018.material}
          position={[0.028, 0.815, -0.014]}
          scale={[0.886, 0.756, 0.849]}
        />
      </mesh>
      <mesh
        geometry={nodes.Plane002.geometry}
        material={materials.libro_verde}
        position={[2.995, 6.308, -5.961]}
        rotation={[1.511, 1.153, -1.516]}
        scale={[0.381, 0.44, 0.164]}
      >
        <mesh
          geometry={nodes.Cube019.geometry}
          material={nodes.Cube019.material}
          position={[0.028, 0.815, -0.014]}
          scale={[0.886, 0.756, 0.849]}
        />
      </mesh>
      <group position={[1.014, 3.121, -5.929]} scale={1.219}>
        <mesh
          geometry={nodes.Cube069.geometry}
          material={materials.consola_bleu_clair}
        />
        <mesh
          geometry={nodes.Cube069_1.geometry}
          material={materials.consola_noir_foncer}
        />
        <mesh
          geometry={nodes.Cube069_2.geometry}
          material={materials.consola_noir_claire}
        />
        <group position={[-0.001, 0.06, -0.083]} scale={1.044}>
          <mesh
            geometry={nodes.Cube070.geometry}
            material={materials.CARTOUCHE}
          />
          <mesh
            geometry={nodes.Cube070_1.geometry}
            material={materials.ventana}
          />
        </group>
      </group>
      <group position={[3.813, 2.125, -4.766]} scale={[1.044, 1.236, 1.044]}>
        <mesh
          geometry={nodes.Cube111.geometry}
          material={materials.CARTOUCHE}
        />
        <mesh
          geometry={nodes.Cube111_1.geometry}
          material={materials.libro_verde}
        />
      </group>
      <group position={[3.813, 2.125, -4.549]} scale={[1.044, 1.236, 1.044]}>
        <mesh
          geometry={nodes.Cube112.geometry}
          material={materials.CARTOUCHE}
        />
        <mesh
          geometry={nodes.Cube112_1.geometry}
          material={materials.libro_amarillo}
        />
      </group>
      <group position={[3.813, 2.125, -4.333]} scale={[1.044, 1.236, 1.044]}>
        <mesh
          geometry={nodes.Cube113.geometry}
          material={materials.CARTOUCHE}
        />
        <mesh
          geometry={nodes.Cube113_1.geometry}
          material={materials.ALFONBRA}
        />
      </group>
      <group
        position={[4.579, 2.125, -4.449]}
        rotation={[-1.511, 0, 0]}
        scale={[1.044, 1.236, 1.044]}
      >
        <mesh
          geometry={nodes.Cube114.geometry}
          material={materials.CARTOUCHE}
        />
        <mesh
          geometry={nodes.Cube114_1.geometry}
          material={materials.libro_azul}
        />
      </group>
      <group position={[1.964, 3.031, -5.18]} scale={0.671}>
        <mesh
          geometry={nodes.Cylinder010_1.geometry}
          material={materials.consola_noir_claire}
        />
        <mesh
          geometry={nodes.Cylinder010_2.geometry}
          material={materials.consola_noir_foncer}
        />
        <mesh
          geometry={nodes.Cylinder010_3.geometry}
          material={materials.rouge}
        />
        <mesh
          geometry={nodes.Cylinder010_4.geometry}
          material={materials.vert}
        />
        <mesh
          geometry={nodes.Cylinder010_5.geometry}
          material={materials.cajon}
        />
        <mesh
          geometry={nodes.Cylinder010_6.geometry}
          material={materials.tapas_ventana}
        />
      </group>
      <group
        position={[2.793, 3.031, -5.18]}
        rotation={[0, -0.995, 0]}
        scale={0.678}
      >
        <mesh
          geometry={nodes.Cylinder022_1.geometry}
          material={materials.consola_noir_claire}
        />
        <mesh
          geometry={nodes.Cylinder022_2.geometry}
          material={materials.consola_noir_foncer}
        />
        <mesh
          geometry={nodes.Cylinder022_3.geometry}
          material={materials.rouge}
        />
        <mesh
          geometry={nodes.Cylinder022_4.geometry}
          material={materials.vert}
        />
        <mesh
          geometry={nodes.Cylinder022_5.geometry}
          material={materials.cajon}
        />
        <mesh
          geometry={nodes.Cylinder022_6.geometry}
          material={materials.tapas_ventana}
        />
      </group>
      <mesh
        geometry={nodes.NurbsPath001.geometry}
        material={materials.cable}
        position={[2.145, 3.881, -5.605]}
        rotation={[0.593, -0.003, 0.002]}
      />
      <mesh
        geometry={nodes.NurbsPath002.geometry}
        material={materials.cable}
        position={[2.388, 3.881, -5.605]}
        rotation={[0.593, -0.003, 0.002]}
      />
      <mesh
        geometry={nodes.Roundcube010.geometry}
        material={materials.metal}
        position={[4.993, 3.97, -4.933]}
        scale={[0.135, 0.135, 0.047]}
      />
      <mesh
        geometry={nodes.Cube031.geometry}
        material={materials.button_negro}
        position={[5.002, 3.961, -4.919]}
        rotation={[1.767, 1.56, -1.761]}
        scale={[0.059, 0.037, 0.086]}
      />
      <mesh
        geometry={nodes.Roundcube011.geometry}
        material={materials.metal}
        position={[4.993, 3.64, -4.933]}
        scale={[0.135, 0.135, 0.047]}
      />
      <mesh
        geometry={nodes.Cube032.geometry}
        material={materials.button_negro}
        position={[4.995, 3.643, -4.895]}
        rotation={[-1.574, 0.903, 1.579]}
        scale={[0.059, 0.037, 0.086]}
      />
      <mesh
        geometry={nodes.Cube033.geometry}
        material={materials.button_negro}
        position={[4.964, 3.292, -4.931]}
        rotation={[0.025, -0.07, 0.019]}
        scale={[0.112, 0.024, 0.035]}
      />
      <mesh
        geometry={nodes.Cube034.geometry}
        material={materials.button_negro}
        position={[4.964, 3.391, -4.931]}
        rotation={[0.025, -0.07, 0.019]}
        scale={[0.112, 0.024, 0.035]}
      />
      <mesh
        geometry={nodes.NurbsPath004.geometry}
        material={materials.cable}
        position={[2.381, 3.018, -6.184]}
        rotation={[0.566, -0.038, 0.024]}
      />
      <mesh
        geometry={nodes.Cylinder016.geometry}
        material={materials["cristal.001"]}
        position={[2.03, 6.612, -5.863]}
        scale={[0.286, 0.383, 0.286]}
      />
      <mesh
        geometry={nodes.Cylinder017.geometry}
        material={materials.aluminium}
        position={[2.03, 7.043, -5.863]}
        scale={[0.304, 0.408, 0.304]}
      />
      <group position={[1.902, 6.352, -5.756]} scale={0.091}>
        <mesh
          geometry={nodes.Sphere004_1.geometry}
          material={materials.blanco}
        />
        <mesh
          geometry={nodes.Sphere004_2.geometry}
          material={materials.libro_azul}
        />
        <mesh
          geometry={nodes.Sphere004_3.geometry}
          material={materials.button_negro}
        />
      </group>
      <group
        position={[2.101, 6.352, -5.756]}
        rotation={[1.539, 0, -0.943]}
        scale={0.091}
      >
        <mesh
          geometry={nodes.Sphere005_1.geometry}
          material={materials.blanco}
        />
        <mesh
          geometry={nodes.Sphere005_2.geometry}
          material={materials.libro_verde}
        />
        <mesh
          geometry={nodes.Sphere005_3.geometry}
          material={materials.button_negro}
        />
      </group>
      <group
        position={[2.158, 6.526, -5.756]}
        rotation={[1.552, -0.026, -0.004]}
        scale={0.091}
      >
        <mesh
          geometry={nodes.Sphere006_1.geometry}
          material={materials.blanco}
        />
        <mesh
          geometry={nodes.Sphere006_2.geometry}
          material={materials.PARQUET1}
        />
        <mesh
          geometry={nodes.Sphere006_3.geometry}
          material={materials.button_negro}
        />
      </group>
      <group
        position={[1.972, 6.526, -5.756]}
        rotation={[1.123, -0.469, 0.715]}
        scale={0.091}
      >
        <mesh
          geometry={nodes.Sphere007_1.geometry}
          material={materials.blanco}
        />
        <mesh
          geometry={nodes.Sphere007_2.geometry}
          material={materials.libro_azul}
        />
        <mesh
          geometry={nodes.Sphere007_3.geometry}
          material={materials.button_negro}
        />
      </group>
      <group
        position={[2.066, 6.676, -5.756]}
        rotation={[1.921, -0.1, 0.097]}
        scale={0.091}
      >
        <mesh
          geometry={nodes.Sphere008_1.geometry}
          material={materials.blanco}
        />
        <mesh
          geometry={nodes.Sphere008_2.geometry}
          material={materials.libro_verde}
        />
        <mesh
          geometry={nodes.Sphere008_3.geometry}
          material={materials.button_negro}
        />
      </group>
      <mesh
        geometry={nodes.Cube036.geometry}
        material={materials.caja}
        position={[3.358, 2.228, 2.851]}
        scale={[1.334, 0.266, 0.864]}
      />
      <mesh
        geometry={nodes.Cube035.geometry}
        material={materials.caja}
        position={[5.297, 1.596, 2.345]}
        rotation={[-1.156, 1.547, 1.144]}
        scale={[0.815, 0.163, 0.528]}
      />
      <mesh
        geometry={nodes.Cube037.geometry}
        material={materials.cornisa}
        position={[-1.266, 5.735, -6.928]}
        scale={[0.546, 1.003, 0.194]}
      />
      <mesh
        geometry={nodes.Cube038.geometry}
        material={materials.caja}
        position={[0, -0.458, 0]}
      />
      <mesh
        geometry={nodes.Cube039.geometry}
        material={materials.cornisa}
        position={[-2.78, 5.735, -6.939]}
        scale={[0.546, 1.003, 0.314]}
      />
      <mesh
        geometry={nodes.Plane005.geometry}
        material={materials.emisivo_ventana}
        position={[-1.266, 5.669, -6.959]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.672, 1.447, 1.175]}
      />
      <mesh
        geometry={nodes.Plane006.geometry}
        material={materials.emisivo_ventana}
        position={[-2.798, 5.805, -6.995]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.672, 1.447, 1.175]}
      />
      <mesh
        geometry={nodes.Cube040.geometry}
        material={materials.caja}
        position={[-1.989, 7.091, -6.266]}
        scale={[1.135, 1, 1.572]}
      />
      <mesh
        geometry={nodes.Cube041.geometry}
        material={materials.persiana}
        position={[-2.033, 6.878, -6.234]}
        scale={[0.957, 1, 1]}
      />
      <mesh
        geometry={nodes.Cube042.geometry}
        material={materials.persiana}
        position={[-2.043, 6.663, -6.234]}
        scale={[0.954, 1, 1]}
      />
      <mesh
        geometry={nodes.Cube043.geometry}
        material={materials.persiana}
        position={[-2.043, 6.431, -6.234]}
        scale={[0.954, 1, 1]}
      />
      <mesh
        geometry={nodes.Cube044.geometry}
        material={materials.persiana}
        position={[-2.043, 6.19, -6.234]}
        scale={[0.954, 1, 1]}
      />
      <mesh
        geometry={nodes.Cube045.geometry}
        material={materials.persiana}
        position={[-2.043, 5.928, -6.234]}
        scale={[0.954, 1, 1]}
      />
      <mesh
        geometry={nodes.Cylinder018.geometry}
        material={materials.consola_noir_claire}
        position={[0, -0.458, 0]}
      />
      <mesh
        geometry={nodes.Cylinder019.geometry}
        material={materials.consola_noir_foncer}
        position={[-0.288, 4.173, -6.271]}
        scale={[0.061, 0.077, 0.056]}
      />
      <group position={[-0.097, -0.037, 0]}>
        <mesh
          geometry={nodes.Plane008.geometry}
          material={materials.PARQUET1}
        />
        <mesh
          geometry={nodes.Plane008_1.geometry}
          material={materials.PARQUET2}
        />
      </group>
      <group position={[-4.694, 6.689, -1.042]}>
        <mesh
          geometry={nodes.Cylinder023_1.geometry}
          material={materials.RELOJ}
        />
        <mesh
          geometry={nodes.Cylinder023_2.geometry}
          material={materials.ALTAVOZ2}
        />
      </group>
      <mesh
        geometry={nodes.Cylinder021.geometry}
        material={materials.aluminium}
        position={[-4.652, 6.689, -1.042]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={0.123}
      />
      <mesh
        geometry={nodes.Cube048.geometry}
        material={materials.ALTAVOZ1}
        position={[-4.634, 6.916, -1.041]}
        scale={[0.008, 0.226, 0.025]}
      />
      <mesh
        geometry={nodes.Cube049.geometry}
        material={materials.ALTAVOZ1}
        position={[-4.62, 6.594, -0.931]}
        rotation={[2.356, -0.188, -0.004]}
        scale={[0.006, 0.167, 0.019]}
      />
      <mesh
        geometry={nodes.Cylinder022.geometry}
        material={materials.tabouret}
        position={[2.267, 1.837, -3.143]}
        scale={[0.615, 0.073, 0.615]}
      />
      <mesh
        geometry={nodes.Cylinder023.geometry}
        material={materials.sobre_escritorio}
        position={[0, -0.458, 0]}
      />
      <mesh
        geometry={nodes.Cylinder024.geometry}
        material={materials.sobre_escritorio}
        position={[0, -0.458, 0]}
      />
      <mesh
        geometry={nodes.Cylinder025.geometry}
        material={materials.sobre_escritorio}
        position={[0, -0.458, 0]}
      />
      <mesh
        geometry={nodes.Cylinder026.geometry}
        material={materials.sobre_escritorio}
        position={[0, -0.458, 0]}
      />
      <group
        position={[-0.951, 0.811, -1.303]}
        rotation={[-0.009, 0, 0]}
        scale={[3.006, 0.097, 3.006]}
      >
        <mesh geometry={nodes.Cube134.geometry} material={materials.ALFONBRA} />
        <mesh geometry={nodes.Cube134_1.geometry} material={materials.blanco} />
      </group>
      <mesh
        geometry={nodes.zapatillas.geometry}
        material={materials.zapatillas}
        position={[5.315, 0.846, -0.726]}
        scale={0.167}
      />
      <mesh
        geometry={nodes.Cube053.geometry}
        material={materials.zapatillas}
        position={[5.315, 0.766, -0.76]}
        scale={0.167}
      />
      <mesh
        geometry={nodes.zapatillas001.geometry}
        material={materials.zapatillas}
        position={[4.465, 0.84, -1.781]}
        rotation={[0, -1.031, 0]}
        scale={0.167}
      />
      <mesh
        geometry={nodes.Cube052.geometry}
        material={materials.zapatillas}
        position={[4.494, 0.759, -1.798]}
        rotation={[0, -1.031, 0]}
        scale={0.167}
      />
      <mesh
        geometry={nodes.note_de_musique001.geometry}
        material={materials.persiana}
        position={[-3.319, 3.695, -4.304]}
        rotation={[-0.688, 0.157, 0.053]}
        scale={0.272}
      />
      <mesh
        geometry={nodes.Plane007.geometry}
        material={materials.suelo}
        position={[0, -0.177, 0]}
        scale={61.229}
      />
      <mesh
        geometry={nodes.mure001.geometry}
        material={materials.emissivo}
        position={[-2.116, 8.447, -3.863]}
        scale={[1.173, 1, 1]}
      />
    </group>
  );
}

useGLTF.preload("/models/habitacion2.glb");
